-- Selecting the column...
SELECT class
FROM Courses    -- The table...
GROUP BY class  -- Grouping by similar class...
-- Counting values and selecting classes with at least 5 students...
HAVING COUNT(*) >= 5;