-- Selecting the customer number...
SELECT customer_number
-- Specifying the table...
FROM Orders
-- Grouping rows on basis of customer number...
GROUP BY customer_number
-- Counting elements in each group and ordering in descending...
ORDER BY COUNT(*) DESC 
-- Extracting only the first element...
LIMIT 1;