class Solution {
    public String shortestCompletingWord(String licensePlate, String[] words) {
        // Converting the plate value to lowercase...
        licensePlate = licensePlate.toLowerCase();
        // Map to store the frequency of lowercase letters...
        Map<Character, Integer> charMap = licensePlate.chars()
        // Filtering lowercase letters excluding numbers and spaces...
        .filter(x -> Character.isLowerCase(x)).mapToObj(ch -> (char)ch)
        .collect(Collectors.toMap(  // Collecting as a map...
            key -> key, value -> 1, Integer::sum
        ));
        // Filtering word from Stream which pass the predicate successfully...
        return Arrays.stream(words).filter(word -> {
            // HashMap for each word...
            Map<Character, Integer> wordMap = new HashMap<>();
            for(int i = 0; i < word.length(); i++)  // Updating the HashMap...
                wordMap.put(word.charAt(i), wordMap.getOrDefault(word.charAt(i), 0)+1);
            // Iterators defined for traversing the map...
            Iterator<Map.Entry<Character, Integer>> iterator = charMap.entrySet().iterator();
            while(iterator.hasNext()) {
                // Extracting each entry of the map sequentially...
                Map.Entry<Character, Integer> entry = iterator.next();
                // Checking the predicate...
                if(wordMap.containsKey(entry.getKey()) && 
                wordMap.get(entry.getKey()) >= entry.getValue())
                    continue;
                else    return false;
            }
            // If for all frequencies the predicate is passed...
            return true;
        // Then sort each string on the basis of length of the String...
        }).sorted(Comparator.comparingInt(String::length)).findFirst().orElse("");
    }
}